version: "3.8"
services:
  backend:
    image: backend:1.0
    build: ./backend
    ports:
      - "8080:8080"
  frontend:
    image: frontend:1.0
    build: ./frontend/
    ports:
      - "4200:4200"