apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
data:
  POSTGRES_USER: myapp
  POSTGRES_PASSWORD: dbpass
  POSTGRES_DB: enrollment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:latest
          name: postgres
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
              name: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: pgpass
data:
  pgpass: cG9zdGdyZXM6NTQzMjplbnJvbGxtZW50Om15YXBwOmRicGFzcw==
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: default
spec:
  # Backup the database every Saturday at 0:00
  schedule: "0 0 * * 6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-backup
              image: postgres:latest
              command: ["/bin/sh"]
              args: ["-c", 'echo "$PGPASS" > /root/.pgpass && chmod 600 /root/.pgpass && pg_dump -U myapp -h postgres enrollment > /var/backups/backup-$(date +"%m-%d-%Y-%H-%M").sql']
              env:
                - name: PGPASS
                  valueFrom:
                    secretKeyRef:
                      name: pgpass
                      key: pgpass
              volumeMounts:
                - mountPath: /var/backups
                  name: postgres-storage
          restartPolicy: Never
          volumes:
            - name: postgres-storage
              hostPath:
                # Ensure the file directory is created.
                path: /var/volumes/postgres-backups
                type: DirectoryOrCreate
