DROP TABLE IF EXISTS STUDENTS_ENROLLMENT_BLOCKS;
DROP TABLE IF EXISTS ENROLLMENT_BLOCKS;
DROP TABLE IF EXISTS STUDENTS;

CREATE TABLE STUDENTS (
    INDEX BIGINT PRIMARY KEY
);

CREATE TABLE ENROLLMENT_BLOCKS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    IS_LIMITED BIT NOT NULL,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    IS_CORRECTION BIT NOT NULL
);

CREATE TABLE STUDENTS_ENROLLMENT_BLOCKS (
    STUDENT_INDEX BIGINT NOT NULL,
    ENROLLMENT_BLOCK_ID BIGINT NOT NULL,
    CONSTRAINT PK_STUDENTS_ENROLLMENT_BLOCKS PRIMARY KEY (STUDENT_INDEX, ENROLLMENT_BLOCK_ID),
    CONSTRAINT FK_STUDENT_ID FOREIGN KEY (STUDENT_INDEX) REFERENCES STUDENTS(INDEX),
    CONSTRAINT FK_ENROLLMENT_BLOCK_ID FOREIGN KEY (ENROLLMENT_BLOCK_ID) REFERENCES ENROLLMENT_BLOCKS(ID)
);

INSERT INTO STUDENTS (INDEX) VALUES (238123);
INSERT INTO ENROLLMENT_BLOCKS (ID, NAME, IS_LIMITED, START_DATE, END_DATE, IS_CORRECTION)
VALUES (1, 'Zapisy Lato 2020/2021', 1, '2021-01-15T08:00:00.000', '2021-01-15T22:00:00.000', 0);
INSERT INTO STUDENTS_ENROLLMENT_BLOCKS (STUDENT_INDEX, ENROLLMENT_BLOCK_ID) VALUES (238123, 1);
